// Code generated by mockery v2.42.0. DO NOT EDIT.

package mockcontroller

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/alexandremahdhaoui/ipxer/internal/types"

	uuid "github.com/google/uuid"
)

// MockContent is an autogenerated mock type for the Content type
type MockContent struct {
	mock.Mock
}

type MockContent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContent) EXPECT() *MockContent_Expecter {
	return &MockContent_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, contentID, attributes
func (_m *MockContent) GetByID(ctx context.Context, contentID uuid.UUID, attributes types.IpxeSelectors) ([]byte, error) {
	ret := _m.Called(ctx, contentID, attributes)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.IpxeSelectors) ([]byte, error)); ok {
		return rf(ctx, contentID, attributes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.IpxeSelectors) []byte); ok {
		r0 = rf(ctx, contentID, attributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, types.IpxeSelectors) error); ok {
		r1 = rf(ctx, contentID, attributes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContent_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockContent_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - contentID uuid.UUID
//   - attributes types.IpxeSelectors
func (_e *MockContent_Expecter) GetByID(ctx interface{}, contentID interface{}, attributes interface{}) *MockContent_GetByID_Call {
	return &MockContent_GetByID_Call{Call: _e.mock.On("GetByID", ctx, contentID, attributes)}
}

func (_c *MockContent_GetByID_Call) Run(run func(ctx context.Context, contentID uuid.UUID, attributes types.IpxeSelectors)) *MockContent_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(types.IpxeSelectors))
	})
	return _c
}

func (_c *MockContent_GetByID_Call) Return(_a0 []byte, _a1 error) *MockContent_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContent_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, types.IpxeSelectors) ([]byte, error)) *MockContent_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContent creates a new instance of MockContent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContent {
	mock := &MockContent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
