filename: "zz_generated.{{ .InterfaceName }}.go"
with-expecter: true

packages:

  # internal/adapter
  github.com/alexandremahdhaoui/ipxer/internal/adapter:
    config:
      all: true
      dir: internal/util/mocks/mockadapter
      outpkg: mockadapter

  # internal/controller
  github.com/alexandremahdhaoui/ipxer/internal/controller:
    config:
      all: true
      dir: internal/util/mocks/mockcontroller
      outpkg: mockcontroller

  # controller-runtime/
  sigs.k8s.io/controller-runtime/pkg/client:
    config:
      dir: internal/util/mocks/mockclient
      outpkg: mockclient
    interfaces:
      Client:
      SubResourceWriter:
