defaults:
  # -- sourceDir is the default directory locating the open api specifications.
  sourceDir: ./api
  # -- destinationDir is the default local directory where the generated packages will be written to.
  destinationDir: ./pkg/generated

specs:
  # # Simple Example:
  # # - The configuration below will read oapi spec from "${.defaults.sourceDir}/simple-example.yaml"
  # # - The generated client code will be written to "${.defaults.destinationDir}/exampleclient/zz_generated.exampleclient.go"
  # # - The generated client code will be written to "${.defaults.destinationDir}/exampleserver/zz_generated.exampleserver.go"
  # - name: example
  #   versions:
  #     - v1
  #   client:
  #     enabled: true
  #     packageName: exampleclient
  #   server:
  #     enabled: true
  #     packageName: exampleserver

  # - name: example-from-remote-http-server
  #   source: https://example.com/api/example.yaml
  #   destinationDir: ./pkg/generated
  #   versions:
  #     - v1
  #   client:
  #     enabled: true
  #     packageName: ipxerclient
  #   server:
  #     enabled: true
  #     packageName: ipxerserver

  # ipxer
  - name: ipxer
    versions:
      - v1
    client:
      enabled: true
      packageName: ipxerclient
    server:
      enabled: true
      packageName: ipxerserver

  # webhook-resolver
  - name: ipxer-webhook-resolver
    versions:
      - v1
    client:
      enabled: true
      packageName: resolverclient
    server:
      enabled: true
      packageName: resolverserver

  # webhook-transformer
  - name: ipxer-webhook-transformer
    versions:
      - v1
    client:
      enabled: true
      packageName: transformerclient
    server:
      enabled: true
      packageName: transformerserver
