name: ipxer

kindenv:
  kubeconfigPath: .ignore.kindenv.kubeconfig.yaml

# -- localContainerRegistry will create if enabled a container registry in the kindenv using the kubeconfig which path
#    is defined by {.kindenv.kubeconfigPath}.
localContainerRegistry:
  # -- enabled defines whether the local container registry must be created or not.
  enabled: true
  # -- creadentialPath defines the output file containing the container registry credentials.
  credentialPath: .ignore.local-container-registry.yaml
  # -- path to CA certificate.
  caCrtPath: .ignore.ca.crt
  # -- namespace where the local container registry will be deployed.
  namespace: local-container-registry

oapiCodegenHelper:
  defaults:
    # -- sourceDir is the default directory locating the open api specifications.
    sourceDir: ./api
    # -- destinationDir is the default local directory where the generated packages will be written to.
    destinationDir: ./pkg/generated

  specs:
    # ipxer
    - name: ipxer
      versions:
        - v1
      client:
        enabled: true
        packageName: ipxerclient
      server:
        enabled: true
        packageName: ipxerserver

    # webhook-resolver
    - name: ipxer-webhook-resolver
      versions:
        - v1
      client:
        enabled: true
        packageName: resolverclient
      server:
        enabled: true
        packageName: resolverserver

    # webhook-transformer
    - name: ipxer-webhook-transformer
      versions:
        - v1
      client:
        enabled: true
        packageName: transformerclient
      server:
        enabled: true
        packageName: transformerserver
