refactoring:
  IMPORTANT: |-
    For the `/config` endpoint, don't use the profile name (only use the config UUID).
    Query the config by UUID by setting the uuid into a label to the profile. 
    The key will hold the uuid; the value will be set to the additionalContent's name.

    => Ongoing

misc:
  Log:
    add logger
  "*.go":
    - wrap errors
  CachePolicies:
    - allow caching for objectRef and webhook content.
    - create multiple caching strategies such as lru, timeout and allow users to choose between multiple strategies.
    - the NoCache policy should be enabled by default. Users who wants to optimize can optimize.
    - NB: implement the cache as lru or a ring buffer of pointers to avoid uncontrolled mem consumptions.
          Also allow other strategies such as timeouts e.g. by creating a small DS to store pointers to cache entries 
          that should be deleted after a timestamp.

impl:
  cmd:
    - config
  driver/webhook:
    - assignment
    - profile

fakes:
  adapterfake:
    - assignment
    - profile
    - resolver
    - transformer

test:
  fix-unit-tests:
    adapter:
    controller:

  unit:
    cmd:
      - cmd
      - config
    driver:
      server:
      webhook:

  integration:
    TODO:
      - define integration
      - scope: kind or "k8s w/o kubelet" (kwok)

  functional-tests:
    TODO:
      - define functional testing for this project.
      - scope: kind/kwok + fakes

  e2e:
    TODO:
      - define e2e
      - scope: create VMs + DHCP server + a kubeadm cluster.
      - considerations:
        - make it quite extensible.
        - think about e2e on bare metal or cloud provider infrastructures.
        - use different k8s distros?
        - use different DHCP server.
        - NB: don't bother using a different hypervisor than KVM.
