misc:
  Log:
    add logger.
  "*.go":
    - wrap errors
  Cache:
    - create an LRU cache for inline configs
  CachePolicies:
    - allow caching for objectRef and webhook content.
    - create multiple caching strategies such as lru, timeout and allow users to choose between multiple strategies.
    - the NoCache policy should be enabled by default. Users who wants to optimize can optimize.
    - NB: Always implement the cache as lru or as a ring buffer of pointers to avoid uncontrolled mem consumptions.
          Also allow other strategies such as timeouts e.g. by creating a small DS to store pointers to cache entries 
          that should be deleted after a timestamp.

impl:
  cmd:
    - config
  driver/webhook:
    - assignment
    - profile

test:
  unit:
    cmd:
      - cmd
      - config
    driver:
      server:
      webhook:

  integration:
    TODO:
      - define integration
      - scope: kind or "k8s w/o kubelet" (kwok)

  e2e:
    TODO:
      - define e2e
      - scope: create VMs + DHCP server + a kubeadm cluster.
      - considerations:
        - make it quite extensible.
        - use different k8s distros (e.g. k3s)
        - use different DHCP server.
        - NB: don't bother using a different hypervisor than KVM.
