// Package resolverserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package resolverserver

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BuildarchSelector.
const (
	BuildarchSelectorArm32 BuildarchSelector = "arm32"
	BuildarchSelectorArm64 BuildarchSelector = "arm64"
	BuildarchSelectorI386  BuildarchSelector = "i386"
	BuildarchSelectorX8664 BuildarchSelector = "x86_64"
)

// Defines values for ResolveParamsBuildarch.
const (
	ResolveParamsBuildarchArm32 ResolveParamsBuildarch = "arm32"
	ResolveParamsBuildarchArm64 ResolveParamsBuildarch = "arm64"
	ResolveParamsBuildarchI386  ResolveParamsBuildarch = "i386"
	ResolveParamsBuildarchX8664 ResolveParamsBuildarch = "x86_64"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// AnyRoutes defines model for anyRoutes.
type AnyRoutes = string

// BuildarchSelector defines model for buildarchSelector.
type BuildarchSelector string

// UuidSelector defines model for uuidSelector.
type UuidSelector = UUID

// N400 defines model for 400.
type N400 = Error

// N401 defines model for 401.
type N401 = Error

// N403 defines model for 403.
type N403 = Error

// N404 defines model for 404.
type N404 = Error

// N500 defines model for 500.
type N500 = Error

// N503 defines model for 503.
type N503 = Error

// ResolveResponse defines model for ResolveResponse.
type ResolveResponse struct {
	Data *string `json:"data,omitempty"`
}

// ResolveParams defines parameters for Resolve.
type ResolveParams struct {
	Uuid      UuidSelector           `form:"uuid" json:"uuid"`
	Buildarch ResolveParamsBuildarch `form:"buildarch" json:"buildarch"`
}

// ResolveParamsBuildarch defines parameters for Resolve.
type ResolveParamsBuildarch string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Resolve a config
	// (GET /{anyRoutes})
	Resolve(ctx echo.Context, anyRoutes AnyRoutes, params ResolveParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Resolve converts echo context to params.
func (w *ServerInterfaceWrapper) Resolve(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "anyRoutes" -------------
	var anyRoutes AnyRoutes

	err = runtime.BindStyledParameterWithOptions("simple", "anyRoutes", ctx.Param("anyRoutes"), &anyRoutes, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter anyRoutes: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResolveParams
	// ------------- Required query parameter "uuid" -------------

	err = runtime.BindQueryParameter("form", true, true, "uuid", ctx.QueryParams(), &params.Uuid)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter uuid: %s", err))
	}

	// ------------- Required query parameter "buildarch" -------------

	err = runtime.BindQueryParameter("form", true, true, "buildarch", ctx.QueryParams(), &params.Buildarch)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter buildarch: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Resolve(ctx, anyRoutes, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/:anyRoutes", wrapper.Resolve)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RW32/jNgz+VwTungbHdhIn1/Nbt3VAgG04tFdsWJENis3EurMllZLT5gr/74Mk50eb",
	"oC2K7slx/In8PpIi+QCFarSSKK2B/AE0J96gRfJvXG4uVWvRv5RoChLaCiUhh2spbltkokRpxVIgMbVk",
	"tkKmSS1FjTFEIBxQc1tBBJI3CPmBxQgIb1tBWEJuqcUITFFhwwMLa5Hc6X9uzgd/88H3ef9MB5/mP36A",
	"COxGO3vGkpAr6LoIFq2oS05FdYU1FlaRs+Qp3LZImz2HHfBZDijbBvIbEOOzKURwfzb9d5pBBJya8Sg8",
	"pxnMTzFpW1G+RMJhnvX/gXAJOfyQ7BOUhK8mub6e/QKdc0VotJImZChLU/colLQorU+g1rUouMtZ8tW4",
	"xD0A3vNG1xiQJUKepWkEDRrDV47ZT7xkjhYaGzFdIzfIigqLb2yjWmJC6tZC91qqF0SKAtfHBeTcXAY3",
	"zlqWDt/GfXjI/Vry1laKxHcsd+Q1qbUoka15LUrmAK5mg+Ugx7yDnvPe8dbsUlHT/zasEcYIuWLKxc/z",
	"CJrHb9M8PtT8q6KFKEuUkUsQKxWTyrKKr5FpJO9ZSWYV40WBxjBbCcMIjWqpwHcQvvMfJGVvk5QdSvpS",
	"4bYEsdxxZXfceG1L1cryPVLGjMbCda8DJ+KJj8nbLtXk8aWaSdfQeM0M0hqJoeO0q1BLG8ZXXEhWc4v0",
	"DtKuJd5rLFz4xCnXQdn4bcoeld8V0loUyFrJ11zUfFHj/6jrhLfYmb1Eo+o1Xvbt8BW6DqYNKY1kRT/m",
	"uPX/Hrf1/h+1+IqFPUXOjb9d2LedmS1JNX4yUuDIUJZaCWm90V6x8xhEHxEKUX+A0FAgByGtn0A9H5ff",
	"VQjuLiun6O9HzU2wucfPj8RF4GfMYf5hOBpjNpl+HODZp8VgOCrHA55NpoNsNJ0Os+HHLE1TiPY8+xH3",
	"lEnnFoOl2qaIFz5F/Vg8r/Gey5KQ/c6rsuKqFRBBSzXkUFmrTZ4kK2GrdhEXqkn4Ft5s0YnQ9yEYj3Pz",
	"xXU9YXwizj/Ptje/nwJL15idzMaNBrlinP2Ji0qpb6yvLHILTS0K7Ktry1fzokI2itMjmnd3dzH3n2NF",
	"q6Q/a5LfZj9f/HF1MRjFaVzZpnZcrbA+xLPPf11cHrmGCNZIJggZxmmcujNKo+RaQA7jOI3HEPlVy5dM",
	"8rDbszr3vkIfY1dVXu+shHx7Zfy5/dJ3c/pi7iHJfoXrohfBj1ahV+CPl7hu/mTLGYWGfMrQDpc87Qd+",
	"NL3inAPtt5GXsMODKf4SdnwwHl/CZgeD53nsJPCdvIaDA/mW0zYNp82+BBhnhZJLsXK3la9cFUDfrGDe",
	"dV33XwAAAP//40PDBiYMAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
