// Package transformerserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package transformerserver

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Buildarch.
const (
	Arm32 Buildarch = "arm32"
	Arm64 Buildarch = "arm64"
	I386  Buildarch = "i386"
	X8664 Buildarch = "x86_64"
)

// Buildarch defines model for Buildarch.
type Buildarch string

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// TransformRequest defines model for TransformRequest.
type TransformRequest struct {
	Attributes *struct {
		Buildarch Buildarch `json:"buildarch"`
		Uuid      UUID      `json:"uuid"`
	} `json:"attributes,omitempty"`
	Content *string `json:"content,omitempty"`
}

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// AnyRoutes defines model for anyRoutes.
type AnyRoutes = string

// N400 defines model for 400.
type N400 = Error

// N401 defines model for 401.
type N401 = Error

// N403 defines model for 403.
type N403 = Error

// N404 defines model for 404.
type N404 = Error

// N500 defines model for 500.
type N500 = Error

// N503 defines model for 503.
type N503 = Error

// TransformResponse defines model for TransformResponse.
type TransformResponse struct {
	Data *string `json:"data,omitempty"`
}

// TransformJSONRequestBody defines body for Transform for application/json ContentType.
type TransformJSONRequestBody = TransformRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Perform a transformation
	// (POST /{anyRoutes})
	Transform(ctx echo.Context, anyRoutes AnyRoutes) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Transform converts echo context to params.
func (w *ServerInterfaceWrapper) Transform(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "anyRoutes" -------------
	var anyRoutes AnyRoutes

	err = runtime.BindStyledParameterWithOptions("simple", "anyRoutes", ctx.Param("anyRoutes"), &anyRoutes, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter anyRoutes: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Transform(ctx, anyRoutes)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/:anyRoutes", wrapper.Transform)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RWTW/jNhD9K8R0T4UsybbszeqWtClgoC2CbIIWDdyClsYWdyWSS1JOvIH+e0FSkuXY",
	"SNIgPSkOhzPvDd98PEImKik4cqMhfQRJFa3QoHK/KN9di9qg+5GjzhSThgkOKdxy9q1GwnLkhq0ZKiLW",
	"xBRIpBJrVmIIATBrKKkpIABOK4R04DEAhd9qpjCH1KgaA9BZgRX1KIxBZW//fXc++ouOvi/bbzz6tPzx",
	"AwRgdtL600YxvoGmaaw/LQXXHm0Sx/aTCW6QG0dGypJl1OKPvmhL4hHwgVayRG+ZI6RJHAdQodZ0Y91f",
	"0JxYmKhNQGSJVCPJCsy+kp2oFWFc1gaaIfQPCteQwg/RPq+RP9XRpVJCeayHybRhrn0Y6y2Jx2/DPh5i",
	"v+W0NoVQ7DvmPXipxJblSLa0ZDmxBvb9vGdPR78Dn/M2cOd2LVTV/q1JxbRmfEOEzZ/D4TlP38Z5OuT8",
	"i1ArlufIA/tAJBeEC0MKukUiUbnIghMjCM0y1JqYgmmiUItaZfgOxPv4nlLyNkrJkNJNgZ0EMe+xknuq",
	"Hbe1qHn+Hk9GtMTMVvIgCHsSY/a2opodFtWC2+KmJdGotqgIWky9Qo3aEbqhjJOSGlTvQO2W44PEzKaP",
	"nQrtmU3fxuxAfp9RbVmGpOZ0S1lJVyX+j7xORAut2xtFubYld902xFcwG/ReJSQqw9qmT43779N22zdg",
	"sfqCmTkFzw6DPvGmw0S6Lu2ctBxthIualTlVWeESzesK0jtg07M5BPBwNv9nnkAAVFXTif/OE1gejYEA",
	"fLaOePjnegTfiSAFxo3z1Dqwwtj4V+mf8xTr/cy68z739sujnBw8he/uR8CoMYqtuhl7eLYapuQ5iexz",
	"1wRQ1yx/6cLt7eLnIz7uYjCIeorRQEcvaiIAF2dYODCeTDGZzT+O8OzTajSe5NMRTWbzUTKZz8fJ+GMS",
	"xzEE+3dqQZ0Y93asdMqmmUPULhnnJT5Qniskv9EiL6ioGQRQqxJSKIyROo2iDTNFvQozUUW0M68664jJ",
	"By+GQ0nf2HHBtNtzzq8WXctsx+faTjRLs7IzlW8IJX/gqhDiK+l1gMouRiXLsK3LDrKkWYFkEsZHSO/v",
	"70PqjkOhNlF7V0e/Ln66/P3z5WgSxmFhqtLCNcy4LC+u/ry8PhUdAtii0p7OOIzD2F4TEjmVDFKYhnE4",
	"hcBtbU6D0WO/sjVOocKr2OrU0V7kNjFdBHd1v0LenZbh3iTaL4TN0ssRtbkQ+e4/Na3ntH5Ugyd6lR2y",
	"wxblDMnKwni6WE78DDwVsbeLjluw2wdecdMa7VfAl2zHg9XpJdvpYCd5yTYZTPvnbWce7+w1GKyR6/p1",
	"VVG1gxSuULmM03323RPbiqcbKyDoD2DZNE3zbwAAAP//jymuObEMAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
