FROM docker.io/golang:1.22 as downloader

WORKDIR /workdir

COPY . ./

RUN go mod download

FROM downloader as builder

ARG GO_BUILD_LDFLAGS

ARG NAME=ipxer-api
ARG INPUT_CMD="./cmd/${NAME}"
ARG OUTPUT_BIN="/bin/${NAME}"

RUN CG0_ENABLED=0 \
    GOOS=linux \
    go build \
      -ldflags "${GO_BUILD_LDFLAGS}" \
      -o "${OUTPUT_BIN}" \
      "${INPUT_CMD}"

FROM gcr.io/distroless/static-debian11

COPY --from=builder ${OUTPUT_BIN} ${OUTPUT_BIN}

CMD [ "/bin/ipxer-api" ]
